nome = input('Digite um nome :')
print('é alfanumerico?', nome.isalnum())
print('é minusculo?', nome.islower())
print('é maiusculo?', nome.isupper())
print('é alfanumerico?', nome.isalpha())
print('é da tabela ascii?', nome.isascii())
print('é um digito ?', nome.isdigit())
print('é decimal?', nome.isdecimal())
print('é numerico?', nome.isnumeric())
print('é espaço?', nome.isspace())
print('é capitalizado?', nome.istitle())
print('pode ser mostrado?', nome.isprintable())
print('é identificavel?', nome.isidentifier())
